
route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'dev-mail:2500'
        auth_username: 
        auth_password: 
        from: 'alert-manager@alert.com'
        to: 'fake@example.com'
        headers:
          subject: 'Prometheus Mail Alerts'