services:
  mockegauge:
    image: ghcr.io/blazingneutron/mock-egauge:latest
    build:
      context: ..
      dockerfile: docker/mockegauge/Dockerfile
    restart: unless-stopped
    
  app:
    image: ghcr.io/blazingneutron/egauge-polling:latest
    build:
      context: ..
      dockerfile: docker/polling/Dockerfile
    restart: unless-stopped
    environment:
      EGAUGE_USER: ${EGAUGE_USER}
      EGAUGE_PASSWORD: ${EGAUGE_PASSWORD}
    volumes:
      - config.json:/app/config.json

  postgres:
    image: postgres
    container_name: grafana-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: ${GRAFANA_DB_USER}
      POSTGRES_PASSWORD: ${GRAFANA_DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - postgres
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    restart: unless-stopped
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: ${GRAFANA_DB_USER}
      GF_DATABASE_PASSWORD: ${GRAFANA_DB_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - ./grafana/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - grafana_data:/var/lib/grafana
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - postgres
      - grafana
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
  
  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    depends_on:
      - postgres
      - grafana
    ports:
      - "${ALERT_MANAGER_PORT:-9093}:9093"
    restart: always
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    environment:
     - GF_SERVER_ROOT_URL=http://grafana:3000/grafana/

  mail:
    container_name: mail
    image: inbucket/inbucket:3.0.3
    ports:
      - '${SMTP_PORT:-2500}:2500' # SMTP
      - '${MAIL_UI_PORT:-9000}:9000' # web interface
      - '${POP3_PORT:-1100}:1100' # POP3

volumes:
  pg_data:
  grafana_data:
